//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 01:59:34 fm CEST 
//


package sequenceplanner.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sequenceplanner.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Owner_QNAME = new QName("", "owner");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sequenceplanner.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bookings.ResourceBooking }
     * 
     */
    public Bookings.ResourceBooking createBookingsResourceBooking() {
        return new Bookings.ResourceBooking();
    }

    /**
     * Create an instance of {@link SequencePlannerProjectFile.Views }
     * 
     */
    public SequencePlannerProjectFile.Views createSequencePlannerProjectFileViews() {
        return new SequencePlannerProjectFile.Views();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link Bookings }
     * 
     */
    public Bookings createBookings() {
        return new Bookings();
    }

    /**
     * Create an instance of {@link OperationData }
     * 
     */
    public OperationData createOperationData() {
        return new OperationData();
    }

    /**
     * Create an instance of {@link SequencePlannerProjectFile.Liasons }
     * 
     */
    public SequencePlannerProjectFile.Liasons createSequencePlannerProjectFileLiasons() {
        return new SequencePlannerProjectFile.Liasons();
    }

    /**
     * Create an instance of {@link CellData.Geo }
     * 
     */
    public CellData.Geo createCellDataGeo() {
        return new CellData.Geo();
    }

    /**
     * Create an instance of {@link Actions.Action }
     * 
     */
    public Actions.Action createActionsAction() {
        return new Actions.Action();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Conditions.Or.SequenceCondition }
     * 
     */
    public Conditions.Or.SequenceCondition createConditionsOrSequenceCondition() {
        return new Conditions.Or.SequenceCondition();
    }

    /**
     * Create an instance of {@link ViewType }
     * 
     */
    public ViewType createViewType() {
        return new ViewType();
    }

    /**
     * Create an instance of {@link Conditions.Or }
     * 
     */
    public Conditions.Or createConditionsOr() {
        return new Conditions.Or();
    }

    /**
     * Create an instance of {@link Rectangle }
     * 
     */
    public Rectangle createRectangle() {
        return new Rectangle();
    }

    /**
     * Create an instance of {@link SequencePlannerProjectFile.Resources }
     * 
     */
    public SequencePlannerProjectFile.Resources createSequencePlannerProjectFileResources() {
        return new SequencePlannerProjectFile.Resources();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link SequencePlannerProjectFile }
     * 
     */
    public SequencePlannerProjectFile createSequencePlannerProjectFile() {
        return new SequencePlannerProjectFile();
    }

    /**
     * Create an instance of {@link Liason }
     * 
     */
    public Liason createLiason() {
        return new Liason();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link CellData }
     * 
     */
    public CellData createCellData() {
        return new CellData();
    }

    /**
     * Create an instance of {@link SequencePlannerProjectFile.Operations }
     * 
     */
    public SequencePlannerProjectFile.Operations createSequencePlannerProjectFileOperations() {
        return new SequencePlannerProjectFile.Operations();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "owner")
    public JAXBElement<String> createOwner(String value) {
        return new JAXBElement<String>(_Owner_QNAME, String.class, null, value);
    }

}
