//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.05 at 04:34:18 PM CEST
//


package sequenceplanner.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="sequenceSet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="childId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="geo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="geometry" type="{}rectangle"/>
 *                   &lt;element name="alternateGeometry" type="{}rectangle" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="refId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="successor" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="expanded" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "CellData")
public class CellData {

    @XmlElement(required = true)
    protected CellData.SequenceSet sequenceSet;
    @XmlElement(required = true)
    protected CellData.Geo geo;
    @XmlAttribute(name = "refId", required = true)
    protected int refId;
    @XmlAttribute(name = "successor")
    protected Integer successor;
    @XmlAttribute(name = "type", required = true)
    protected int type;
    @XmlAttribute(name = "expanded", required = true)
    protected boolean expanded;

    /**
     * Gets the value of the sequenceSet property.
     *
     * @return
     *     possible object is
     *     {@link CellData.SequenceSet }
     *
     */
    public CellData.SequenceSet getSequenceSet() {
        return sequenceSet;
    }

    /**
     * Sets the value of the sequenceSet property.
     *
     * @param value
     *     allowed object is
     *     {@link CellData.SequenceSet }
     *
     */
    public void setSequenceSet(CellData.SequenceSet value) {
        this.sequenceSet = value;
    }

    /**
     * Gets the value of the geo property.
     *
     * @return
     *     possible object is
     *     {@link CellData.Geo }
     *
     */
    public CellData.Geo getGeo() {
        return geo;
    }

    /**
     * Sets the value of the geo property.
     *
     * @param value
     *     allowed object is
     *     {@link CellData.Geo }
     *
     */
    public void setGeo(CellData.Geo value) {
        this.geo = value;
    }

    /**
     * Gets the value of the refId property.
     *
     */
    public int getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     *
     */
    public void setRefId(int value) {
        this.refId = value;
    }

    /**
     * Gets the value of the successor property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getSuccessor() {
        return successor;
    }

    /**
     * Sets the value of the successor property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setSuccessor(Integer value) {
        this.successor = value;
    }

    /**
     * Gets the value of the type property.
     *
     */
    public int getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     */
    public void setType(int value) {
        this.type = value;
    }

    /**
     * Gets the value of the expanded property.
     *
     */
    public boolean isExpanded() {
        return expanded;
    }

    /**
     * Sets the value of the expanded property.
     *
     */
    public void setExpanded(boolean value) {
        this.expanded = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="geometry" type="{}rectangle"/>
     *         &lt;element name="alternateGeometry" type="{}rectangle" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geometry",
        "alternateGeometry"
    })
    public static class Geo {

        @XmlElement(required = true)
        protected Rectangle geometry;
        protected Rectangle alternateGeometry;

        /**
         * Gets the value of the geometry property.
         *
         * @return
         *     possible object is
         *     {@link Rectangle }
         *
         */
        public Rectangle getGeometry() {
            return geometry;
        }

        /**
         * Sets the value of the geometry property.
         *
         * @param value
         *     allowed object is
         *     {@link Rectangle }
         *
         */
        public void setGeometry(Rectangle value) {
            this.geometry = value;
        }

        /**
         * Gets the value of the alternateGeometry property.
         *
         * @return
         *     possible object is
         *     {@link Rectangle }
         *
         */
        public Rectangle getAlternateGeometry() {
            return alternateGeometry;
        }

        /**
         * Sets the value of the alternateGeometry property.
         *
         * @param value
         *     allowed object is
         *     {@link Rectangle }
         *
         */
        public void setAlternateGeometry(Rectangle value) {
            this.alternateGeometry = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="childId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "childId"
    })
    public static class SequenceSet {

        @XmlElement(type = Integer.class)
        protected List<Integer> childId;

        /**
         * Gets the value of the childId property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the childId property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChildId().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         *
         *
         */
        public List<Integer> getChildId() {
            if (childId == null) {
                childId = new ArrayList<Integer>();
            }
            return this.childId;
        }

    }

}
