//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.07.13 at 07:03:22 PM CEST
//


package sequenceplanner.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="condKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="condValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "condition")
public class Condition {

    @XmlAttribute(name = "condKey")
    protected String condKey;
    @XmlAttribute(name = "condValue")
    protected String condValue;

    /**
     * Gets the value of the condKey property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCondKey() {
        return condKey;
    }

    /**
     * Sets the value of the condKey property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCondKey(String value) {
        this.condKey = value;
    }

    /**
     * Gets the value of the condValue property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCondValue() {
        return condValue;
    }

    /**
     * Sets the value of the condValue property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCondValue(String value) {
        this.condValue = value;
    }

}