//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.18 at 08:27:41 AM CEST 
//


package sequenceplanner.weightNonBlocking.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sequenceplanner.weightNonBlocking.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sequenceplanner.weightNonBlocking.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SeamType }
     * 
     */
    public SeamType createSeamType() {
        return new SeamType();
    }

    /**
     * Create an instance of {@link ResourcesType }
     * 
     */
    public ResourcesType createResourcesType() {
        return new ResourcesType();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link BlockType }
     * 
     */
    public BlockType createBlockType() {
        return new BlockType();
    }

    /**
     * Create an instance of {@link SeamsType }
     * 
     */
    public SeamsType createSeamsType() {
        return new SeamsType();
    }

    /**
     * Create an instance of {@link SeamAssemblyType }
     * 
     */
    public SeamAssemblyType createSeamAssemblyType() {
        return new SeamAssemblyType();
    }

    /**
     * Create an instance of {@link BlocksType }
     * 
     */
    public BlocksType createBlocksType() {
        return new BlocksType();
    }

}
