//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.18 at 08:27:41 AM CEST 
//


package sequenceplanner.weightNonBlocking.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}seamsType"/>
 *         &lt;element ref="{}blocksType"/>
 *         &lt;element ref="{}resourcesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seamsType",
    "blocksType",
    "resourcesType"
})
@XmlRootElement(name = "seamAssemblyType")
public class SeamAssemblyType {

    @XmlElement(required = true)
    protected SeamsType seamsType;
    @XmlElement(required = true)
    protected BlocksType blocksType;
    @XmlElement(required = true)
    protected ResourcesType resourcesType;

    /**
     * Gets the value of the seamsType property.
     * 
     * @return
     *     possible object is
     *     {@link SeamsType }
     *     
     */
    public SeamsType getSeamsType() {
        return seamsType;
    }

    /**
     * Sets the value of the seamsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeamsType }
     *     
     */
    public void setSeamsType(SeamsType value) {
        this.seamsType = value;
    }

    /**
     * Gets the value of the blocksType property.
     * 
     * @return
     *     possible object is
     *     {@link BlocksType }
     *     
     */
    public BlocksType getBlocksType() {
        return blocksType;
    }

    /**
     * Sets the value of the blocksType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlocksType }
     *     
     */
    public void setBlocksType(BlocksType value) {
        this.blocksType = value;
    }

    /**
     * Gets the value of the resourcesType property.
     * 
     * @return
     *     possible object is
     *     {@link ResourcesType }
     *     
     */
    public ResourcesType getResourcesType() {
        return resourcesType;
    }

    /**
     * Sets the value of the resourcesType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourcesType }
     *     
     */
    public void setResourcesType(ResourcesType value) {
        this.resourcesType = value;
    }

}
