/*
 * DescriptionPanel.java
 *
 * Created on 2011-jul-06, 01:03:51
 */
package sequenceplanner.gui.view.attributepanel;

import java.awt.event.ActionListener;
import java.awt.event.FocusListener;

/**
 *
 * @author QW4z1
 */
public class DescriptionPanel extends javax.swing.JPanel {

    /** Creates new form DescriptionPanel */
    public DescriptionPanel() {
        initComponents();
    }

    public DescriptionPanel(String description) {
        this();
        setDescription(description);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Description");

        descriptionTextField.setToolTipText("Press ENTER to save description");
        descriptionTextField.setActionCommand("set description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1).addComponent(descriptionTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public String getDescription() {
        return descriptionTextField.getText();
    }

    public void setDescription(String description) {
        descriptionTextField.setText(description);
    }

    /**
     * Adds an ActionListener to the DescriptionTextField
     * @param l the ActionListener
     */
    public void addActionListener(ActionListener l) {
        descriptionTextField.addActionListener(l);
    }


    @Override
    public void addFocusListener(FocusListener l) {
        descriptionTextField.addFocusListener(l);
    }
}
